FROM java:8-jdk

# Install gradle
#RUN apt-get update
#RUN apt-get -y install gradle

#RUN gradle bootJar

# Heroku Procfile
ADD Procfile /app/Procfile

# Adding jar
ADD build/libs/app.jar /app/app.jar

WORKDIR /app

# Run the image as a non-root user
RUN useradd -d /code -m myuser
USER myuser

CMD java -jar app.jar --server.port=$PORT
